
import type { Product } from './types';

export const IPHONE_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'iPhone 15 Pro',
    category: 'Pro Models',
    price: 999,
    description: 'The ultimate iPhone, powered by the A17 Pro chip. Pro-grade camera system and a durable, lightweight titanium design.',
    imageUrl: 'https://images.unsplash.com/photo-1697059327293-089405a78f69?q=80&w=600&auto=format&fit=crop',
    specs: {
      storage: ['128GB', '256GB', '512GB', '1TB'],
      colors: ['Natural Titanium', 'Blue Titanium', 'White Titanium', 'Black Titanium'],
      display: '6.1-inch Super Retina XDR display with ProMotion',
      camera: 'Pro camera system (48MP Main, Ultra Wide, Telephoto)',
    },
    stock: 1500,
    rating: 4.9,
    reviewCount: 3450,
  },
  {
    id: 2,
    name: 'iPhone 15',
    category: 'Standard Models',
    price: 799,
    description: 'A total powerhouse. With the Dynamic Island, 48MP Main camera, and USB-C. All in a durable color-infused glass and aluminum design.',
    imageUrl: 'https://images.unsplash.com/photo-1700202948197-004d3e83d8e8?q=80&w=600&auto=format&fit=crop',
    specs: {
      storage: ['128GB', '256GB', '512GB'],
      colors: ['Blue', 'Pink', 'Yellow', 'Green', 'Black'],
      display: '6.1-inch Super Retina XDR display',
      camera: 'Advanced dual-camera system (48MP Main, Ultra Wide)',
    },
    stock: 2500,
    rating: 4.8,
    reviewCount: 5120,
  },
  {
    id: 3,
    name: 'iPhone 15 Pro Max',
    category: 'Pro Models',
    price: 1199,
    description: 'The largest and most advanced iPhone. Features the A17 Pro chip, the longest optical zoom in iPhone history, and a massive 6.7-inch display.',
    imageUrl: 'https://images.unsplash.com/photo-1697250723842-12122b51347a?q=80&w=600&auto=format&fit=crop',
    specs: {
      storage: ['256GB', '512GB', '1TB'],
      colors: ['Natural Titanium', 'Blue Titanium', 'White Titanium', 'Black Titanium'],
      display: '6.7-inch Super Retina XDR display with ProMotion',
      camera: 'Pro camera system (48MP Main, Ultra Wide, 5x Telephoto)',
    },
    stock: 1200,
    rating: 4.9,
    reviewCount: 4200,
  },
  {
    id: 4,
    name: 'iPhone SE',
    category: 'Special Edition',
    price: 429,
    description: 'Serious power. Pocket-friendly size. Features the powerful A15 Bionic chip and a durable design. A great value iPhone.',
    imageUrl: 'https://images.unsplash.com/photo-1592286360520-16831d117a26?q=80&w=600&auto=format&fit=crop',
    specs: {
      storage: ['64GB', '128GB', '256GB'],
      colors: ['Midnight', 'Starlight', '(PRODUCT)RED'],
      display: '4.7-inch Retina HD display',
      camera: 'Advanced 12MP camera',
    },
    stock: 5000,
    rating: 4.6,
    reviewCount: 8900,
  },
   {
    id: 5,
    name: 'iPhone 14',
    category: 'Standard Models',
    price: 699,
    description: 'As amazing as ever. With a durable design, great cameras, and essential safety features.',
    imageUrl: 'https://images.unsplash.com/photo-1663450302321-21e105e9a9b9?q=80&w=600&auto=format&fit=crop',
    specs: {
      storage: ['128GB', '256GB', '512GB'],
      colors: ['Blue', 'Purple', 'Yellow', 'Midnight', 'Starlight', '(PRODUCT)RED'],
      display: '6.1-inch Super Retina XDR display',
      camera: 'Dual-camera system (12MP Main, Ultra Wide)',
    },
    stock: 3500,
    rating: 4.7,
    reviewCount: 6500,
  },
   {
    id: 6,
    name: 'iPhone 14 Plus',
    category: 'Standard Models',
    price: 799,
    description: 'Think big with a larger 6.7-inch display and all-day battery life. An excellent choice for media consumption.',
    imageUrl: 'https://images.unsplash.com/photo-1664478546384-57f19d2906b8?q=80&w=600&auto=format&fit=crop',
    specs: {
      storage: ['128GB', '256GB', '512GB'],
      colors: ['Blue', 'Purple', 'Yellow', 'Midnight', 'Starlight', '(PRODUCT)RED'],
      display: '6.7-inch Super Retina XDR display',
      camera: 'Dual-camera system (12MP Main, Ultra Wide)',
    },
    stock: 2800,
    rating: 4.7,
    reviewCount: 5800,
  },
];
